
---
- name: Create inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add nodes
      ansible.builtin.add_host:
        name: "{{ item }}"
        ansible_ssh_host: "{{ item }}"
        ansible_ssh_port: "{{ lookup('ansible.builtin.env', 'BASTION_PORT') }}"
        ansible_ssh_user: "{{ lookup('ansible.builtin.env', 'BASTION_USER') }}"
        ansible_ssh_pass: "{{ lookup('ansible.builtin.env', 'BASTION_PASSWORD') }}"
        ansible_python_interpreter: /usr/libexec/platform-python
      loop:
        - controller
        - vscode

- name: Demo Playbook for the ansible-runner API
  hosts: all:!localhost
  gather_facts: false
  become: false
  tasks:
    - name: Simple debug task
      ansible.builtin.debug:
        msg: "Hello Runner"